version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dhruv@thakur16
      MYSQL_DATABASE: Crowdfunding
      MYSQL_USER: root
      MYSQL_PASSWORD: Dhruv@thakur16
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
